# Generated by Django 6.0.1 on 2026-01-12 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('preview_image', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('linkedin', models.URLField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('career_objective', models.TextField()),
                ('hsc', models.TextField(blank=True)),
                ('ssc', models.TextField(blank=True)),
                ('fe', models.TextField(blank=True)),
                ('se', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('skills', models.TextField()),
                ('projects', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('ats_score', models.IntegerField(default=0)),
                ('analyzed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
