# Generated by Django 6.0.1 on 2026-01-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_resume_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='fe',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='hsc',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='se',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='ssc',
        ),
        migrations.AddField(
            model_name='resume',
            name='edu_cgpa',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='edu_class',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='edu_college',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='edu_qualification',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='edu_university',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='edu_year',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
    ]
