# Generated by Django 6.0.1 on 2026-01-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_resume_fe_remove_resume_hsc_remove_resume_se_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='dob',
            field=models.DateField(default='Na'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
    ]
